work_group: ${PRIMUS_TEAM:amd}
user_name: ${PRIMUS_USER:root}
exp_name: ${PRIMUS_EXP_NAME:grok2-pretrain}
workspace: ./output

modules:
  pre_trainer:
    config: pre_trainer.yaml
    framework: megatron
    model: grok2.yaml
    overrides:
      wandb_project: "Primus_Grok2_Pretrain"
      # disable_wandb: false
      # disable_tensorboard: false
      stderr_sink_level: DEBUG

      # moe
      moe_router_force_load_balancing: true
      moe_router_dtype: null
      log_avg_skip_iterations: 2
      log_avg_reset_interval: 50

      # hyber parameters
      train_iters: 10
      micro_batch_size: 2
      global_batch_size: 128
      seq_length: 8192
      max_position_embeddings: 8192
      lr: 1.0e-5
      min_lr: 0.0
      lr_warmup_iters: 2
      lr_decay_iters: null
      lr_decay_style: cosine
      weight_decay: 0.1
      adam_beta1: 0.9
      adam_beta2: 0.95
      eod_mask_loss: true
      init_method_std: 0.008
      norm_epsilon: 1.0e-6

      # parallel (for 8 nodes)
      tensor_model_parallel_size: 1
      pipeline_model_parallel_size: 4
      num_virtual_stages_per_pipeline_rank: 4
      expert_model_parallel_size: 8
      overlap_grad_reduce: true
      overlap_param_gather: true

      # recompute
      recompute_granularity: full # full, selective
      recompute_method: block # uniform, block
      recompute_num_layers: 8 # int

      # data
      mock_data: true
      train_data_path: null
      valid_data_path: null
      test_data_path: null

      # fusion
      moe_permute_fusion: false
      gradient_accumulation_fusion: false
      moe_use_legacy_grouped_gemm: true
      cross_entropy_fusion_impl: "te"
      cross_entropy_loss_fusion: true

      # ckpt
      finetune: false
      auto_continue_train: false
      load: null
      no_load_optim: null
      no_load_rng: null
      save: null
      save_interval: 20000
      no_save_optim: null
      no_save_rng: null
      disable_last_saving: true
      ckpt_format: torch
