job:
  dump_folder: "./outputs"
  description: "Llama 3 8B training"

model:
  name: "llama3"
  flavor: "8B"
  hf_assets_path: "meta-llama/Meta-Llama-3-8B"
  converters:
    - quantize.linear.float8
    - quantize.grouped_mm.float8
