job:
  dump_folder: "./outputs"
  description: "Llama 3 70B training"

model:
  name: "llama3"
  flavor: "70B"
  hf_assets_path: "meta-llama/Llama-3.3-70B-Instruct"
  converters:
    - quantize.linear.float8
    - quantize.grouped_mm.float8
